configurationset:
  - configuration:
      name: postgresql_config
      uri: postgresql://ep-plain-art-a51h21e3-pooler.us-east-2.aws.neon.tech/neondb?user=neondb_owner&password=npg_uqBRF6Zm4DTS
  - configuration:
      name: edamam
      app_id: 65d4abb7
      app_key: c0521422394279c810946adb9d02fdf7
